# Usage:
# 
# name: <name of the workflow>
# on:
#   push:
#     paths:
#       - <path>
#   workflow_dispatch:
# jobs:
#   build-and-test:
#     uses: MichaelDiers/github-workflows/.github/workflows/dotnet-build-and-test.yaml@main
#     with:
#       solution-directory: <path to the folder that contains the solution file>
#
name: build and test dotnet solution
on:
  workflow_call:
    inputs:
      solution-directory:
        required: true
        type: string
      runs-on:
        default: ubuntu-latest
        type: string
      dotnet-version:
        default: 9.0.x
        type: string
jobs:
  build-and-test:
    runs-on: ${{inputs.runs-on}}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{inputs.dotnet-version}}
    - name: build
      run: dotnet build --configuration Release 
      working-directory: ${{inputs.solution-directory}}
    - name: test
      run: dotnet test --configuration Release --no-build
      working-directory: ${{inputs.solution-directory}}
