# Info:
# - uses altcover for code coverage
# Usage:
# - set initial data in csproj:
# -- set Version
# 
# name: <name of the workflow>
# on:
#   push:
#     paths:
#       - <path>
#   workflow_dispatch:
# jobs:
#   create-code-coverage-page:
#     uses: MichaelDiers/github-workflows/.github/workflows/dotnet-code-coverage-page.yaml@main
#     with:
#       test-project-name: <name of the test project without .csproj>
#       solution-directory: <path to the folder that contains the solution file>
#
name: add code coverage results to github pages
on:
  workflow_call:
    inputs:
      test-project-name:
        required: true
        type: string
      solution-directory:
        required: true
        type: string
      test-project-extension:
permissions:
  contents: read
jobs:
  extract-version:
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-project-version.yaml@main
    with:
      project-path: ${{inputs.solution-directory}}/${{inputs.test-project-name}}/${{inputs.test-project-name}}.csproj
  coverage:
    needs: extract-version
    runs-on: ubuntu-latest
    env:
      ALTCOVER_XML: ../../doc/coverage/${{inputs.test-project-name}}-altcover.xml
      SOLUTION_DIRECTORY: ${{inputs.solution-directory}}
      TEST_CSPROJ: ${{inputs.solution-directory}}/${{inputs.test-project-name}}/${{inputs.test-project-name}}.csproj
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: add altcover
      run: dotnet add ${{env.TEST_CSPROJ}} package altcover
    - name: build
      run: dotnet build --configuration Release 
      working-directory: ${{env.SOLUTION_DIRECTORY}}
    - name: test
      run: dotnet test --configuration Release /p:AltCover=true --no-build --no-restore /p:AltCoverReport="${{ env.ALTCOVER_XML }}" /p:AltCoverAssemblyFilter=xunit.*
      working-directory: ${{env.SOLUTION_DIRECTORY}}
