# Info:
# - Uses react scripts to build the react application and deploys to github pages.
# Usage:
# - github pages 
#  - enable
#  - set source to GitHub Actions
# 
# name: <name of the workflow>
# on:
#   push:
#     paths:
#       - <path>
#   workflow_dispatch:
# permissions:
#   contents: read
#   id-token: write
#   pages: write
# jobs:
#   react-app-to-github-pages:
#     uses: MichaelDiers/github-workflows/.github/workflows/react-app-to-github-pages.yaml@main
#     with:
#       add-build-info: <if true add a simple build info to the static files, otherwise the step is skipped> (default: false)
#       build-info-file-name: <name of the build info file> (default: build.html)
#       build-directory: <path to build output directory relative to the working-directory> (default: build)
#       working-directory: <path to folder that contains the react app> (required)
#
name: build react app and deploy to github pages
on:
  workflow_call:
    inputs:
      add-build-info:
        default: false
        type: boolean
      build-info-file-name:
        default: build.html
        type: string
      build-directory:
        default: build
        type: string
      working-directory:
        required: true
        type: string
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  build-and-deploy:
    env:
      Add_BUILD_INFO: ${{inputs.add-build-info}}
      BUILD_INFO_FILE: ${{inputs.working-directory}}/${{inputs.build-directory}}/static/${{inputs.build-info-file-name}}
      PAGES_DIRECTORY: ${{inputs.working-directory}}/${{inputs.build-directory}}
      WORKING_DIRECTORY: ${{inputs.working-directory}}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install
      run: npm install
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: build
      run: npm run build
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: add build info
      if: ${{ env.Add_BUILD_INFO == true || env.Add_BUILD_INFO == 'true'}}
      run: echo "${{github.run_number}}" > ${{env.BUILD_INFO_FILE}}
    - name: setup github pages
      uses: actions/configure-pages@v4
    - name: upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.PAGES_DIRECTORY }}
    - name: deploy to github pages
      uses: actions/deploy-pages@v4
