# Info:
# - Uses react scripts to build the react application and deploys to github pages. 
#   Therefore 'npm run build' is expected to build the react app.
# Usage:
# - github pages 
#  - enable
#  - set source to GitHub Actions
# 
# name: <name of the workflow>
# on:
#   push:
#     paths:
#       - <path>
#   workflow_dispatch:
# permissions:
#   contents: read
#   id-token: write
#   pages: write
# jobs:
#   react-app-to-github-pages:
#     uses: MichaelDiers/github-workflows/.github/workflows/react-ci.yaml@main
#     with:
#       add-build-info: <if true add a simple build info to the static files, otherwise the step is skipped> (default: false)
#       build-info-file-name: <name of the build info file> (default: build.html)
#       build-directory: <path to build output directory relative to the working-directory> (default: build)
#       deploy-to-pages: <if true deploy to github pages, otherwise the deployment is skipped> (default: false)
#       set-homepage: <if true set the homepage json entry of the package.json to https://repo_owner.github.io/repo_name, otherwise the step is skipped> (default: false)
#                     Does not check if the json entry already exists.
#       use-stylelint: <if true run stylelint for scss files, otherwise the stylelint is skipped. 
#                      Expects 'npm run stylelint' in the specified working-directory to be executable> (default: false)
#       working-directory: <path to folder that contains the react app> (required)
#
name: react-ci
on:
  workflow_call:
    inputs:
      add-build-info:
        default: false
        type: boolean
      build-info-file-name:
        default: build.html
        type: string
      build-directory:
        default: build
        type: string
      deploy-to-pages:
        default: false
        type: boolean
      set-homepage:
        default: false
        type: boolean
      use-stylelint:
        default: false
        type: boolean
      working-directory:
        required: true
        type: string
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  build-and-deploy:
    env:
      ADD_BUILD_INFO: ${{inputs.add-build-info}}
      BUILD_INFO_FILE: ${{inputs.working-directory}}/${{inputs.build-directory}}/static/${{inputs.build-info-file-name}}
      DEPLOY_TO_PAGES: ${{inputs.deploy-to-pages}}
      PAGES_DIRECTORY: ${{inputs.working-directory}}/${{inputs.build-directory}}
      SET_HOMEPAGE: ${{inputs.set-homepage}}
      USE_STYLELINT: ${{inputs.use-stylelint}}
      WORKING_DIRECTORY: ${{inputs.working-directory}}
      HOMEPAGE: https:\/\/${{github.repository_owner}}.github.io\/${{github.event.repository.name}}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install
      run: npm install
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: stylelint
      if: ${{ env.USE_STYLELINT == true || env.USE_STYLELINT == 'true'}}
      run: npm run stylelint -- --mw 0
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: set homepage
      if: ${{ env.SET_HOMEPAGE == true || env.SET_HOMEPAGE == 'true'}}
      run: sed -i 's/"name":/"homepage":"${{env.HOMEPAGE}}","name":/' package.json
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: cat
      run: cat package.json
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: build
      run: npm run build
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: add build info
      if: ${{ env.ADD_BUILD_INFO == true || env.ADD_BUILD_INFO == 'true'}}
      run: echo "build ${{github.run_number}}<br>$(date +'%Y-%m-%dT%H:%M:%S')" > ${{env.BUILD_INFO_FILE}}
    - name: setup github pages
      if: ${{ env.DEPLOY_TO_PAGES == true || env.DEPLOY_TO_PAGES == 'true'}}
      uses: actions/configure-pages@v4
    - name: upload artifact
      if: ${{ env.DEPLOY_TO_PAGES == true || env.DEPLOY_TO_PAGES == 'true'}}
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.PAGES_DIRECTORY }}
    - name: deploy to github pages
      if: ${{ env.DEPLOY_TO_PAGES == true || env.DEPLOY_TO_PAGES == 'true'}}
      uses: actions/deploy-pages@v4
